
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Frame2 extends javax.swing.JFrame {
     String nol_jam, nol_menit, nol_detik;
    
    

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        setTanggal();
        setJam();
        
        
    }
    
    
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kasir = new javax.swing.JTextField();
        b8 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        harga1 = new javax.swing.JTextField();
        b9 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        print = new javax.swing.JButton();
        Hasil1 = new javax.swing.JLabel();
        taa = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));
        jPanel1.setLayout(null);
        jPanel1.add(id);
        id.setBounds(130, 70, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel1.setText("ID Barang");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel2.setText("Nama  Barang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 120, 120, 30);
        jPanel1.add(nama);
        nama.setBounds(130, 120, 170, 30);
        jPanel1.add(jumlah);
        jumlah.setBounds(130, 170, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel3.setText("Jumlah  Barang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 170, 116, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel4.setText("Harga Barang");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 230, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel6.setText("Diskon Harga");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 280, 120, 30);
        jPanel1.add(kasir);
        kasir.setBounds(130, 380, 170, 30);

        b8.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b8.setText("Tanggal ");
        jPanel1.add(b8);
        b8.setBounds(10, 330, 90, 30);
        jPanel1.add(Tanggal);
        Tanggal.setBounds(130, 330, 170, 30);
        jPanel1.add(harga1);
        harga1.setBounds(130, 230, 170, 30);

        b9.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b9.setText("Nama Kasir");
        jPanel1.add(b9);
        b9.setBounds(10, 380, 90, 30);
        jPanel1.add(diskon);
        diskon.setBounds(130, 280, 170, 30);

        Total.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        Total.setText("Total");
        jPanel1.add(Total);
        Total.setBounds(10, 420, 90, 30);
        jPanel1.add(total);
        total.setBounds(130, 420, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 310, 490);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdBarang", "Nama", "Jumlah", "Harga", "Tanggal", "NamaKasir", "Total"
            }
        ));
        jScrollPane2.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 780, 402);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(340, 180, 800, 430);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(null);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(40, 10, 110, 30);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(160, 10, 110, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(290, 10, 110, 30);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh);
        refresh.setBounds(410, 10, 110, 30);

        edit1.setText("Edit");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        jPanel3.add(edit1);
        edit1.setBounds(530, 10, 110, 30);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(650, 10, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(340, 120, 800, 50);

        Hasil1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(Hasil1);
        Hasil1.setBounds(880, 80, 220, 40);

        taa.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(taa);
        taa.setBounds(880, 0, 220, 40);

        labeljam.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(labeljam);
        labeljam.setBounds(880, 30, 220, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    
                
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        String tanggal=dateFormat.format(Tanggal.getDate());
        

        if ("".equals(id.getText())||"".equals(nama.getText())||"".equals(jumlah.getText())||"".equals(harga1.getText()) || "".equals(kasir.getText())||"".equals(tanggal)) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi data Anda","Error", JOptionPane.WARNING_MESSAGE);
            
        }
        
        else{
          
            String SQL="INSERT INTO tb_beli(IdBarang,Nama,Jumlah,Total,Diskon,Tanggal)"+
                    "VALUES('"+id.getText()+"','"+nama.getText()+"','"+jumlah.getText()+"','"+hasile+"','"+kasir.getText()+"','"+tanggal+"')";
            int status=KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal disimpan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    

    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data!","",JOptionPane.YES_NO_OPTION);
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            String IdBarang = tabel.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM tb_beli WHERE NIS='"+IdBarang+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Barisnya Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Tanggal.setDate(null);
        nama.setText("");
        jumlah.setText("");
       
        kasir.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        int regane1,regane2,regane3,hasile;
        
        regane1=Integer.parseInt(String.valueOf(harga1.getText()));
        regane2=Integer.parseInt(String.valueOf(harga2.getText()));
        regane3=Integer.parseInt(String.valueOf(harga3.getText()));
        hasile = regane1 + regane2 + regane3; 
        
        int baris = tabel.getSelectedRow();
        String nobar = tabel.getValueAt(baris, 1).toString();
        if ("".equals(id.getText()) || "".equals(nama.getText()) || "".equals(jumlah.getText())||"".equals(harga3.getText())||"".equals(hasile)||"".equals(kasir.getText())||"".equals(tanggal)){

            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }else{
           
            String SQL ="UPDATE `tb_beli` SET `IdBarang`='"+id.getText()
            +"',`Nama`='"+nama.getText()
            +"',`Jumlah`='"+jumlah.getText()
            +"',`Harga'='"+harga3.getText()
            +"',`Diskon`='"+kasir.getText()
                              
           +"' WHERE NIS='"+nobar+"'";

            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this,"Data berhasil di Update","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this,"Data gagal di Update","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_edit1ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat ("Biodata bla");
        MessageFormat footer = new MessageFormat ("bla");

        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch(java.awt.print.PrinterException e) {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil1;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton edit1;
    private javax.swing.JTextField harga1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kasir;
    private javax.swing.JLabel labeljam;
    private javax.swing.JTextField nama;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JLabel taa;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[]={"IdBarang","Nama","Jumlah","Total","Diskon","Tanggal"};
        DefaultTableModel dtm=new DefaultTableModel(null, kolom);
        String SQL="SELECT * FROM tb_beli";
        ResultSet rs=KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String IdBarang=rs.getString(1);
                String Nama=rs.getString(2);
                String Jumlah=rs.getString(3);
                String Total=rs.getString(4);
                String Diskon=rs.getString(5);
                String Tanggal=rs.getString(6);
        
                String data[]={IdBarang,Nama,Jumlah,Total,Diskon,Tanggal};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
        //Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }
    
    public void setTanggal() {
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new
       java.text.SimpleDateFormat("dd/MM/yyyy");
       taa.setText(kal.format(skrg));
    }
    
    
    
    public void setJam() {
       ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
                
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if (nilai_jam<=9){
                    nol_jam = "0";
                } if (nilai_menit <= 9) {
                    nol_menit = "0";
                } if (nilai_detik <= 9){
                    nol_detik = "0";
                }
               
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Hasil1.setText(jam+":"+menit+":"+detik);
            }
        };
    new Timer(100, taskPerformer).start();
}
}
