
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Frame2 extends javax.swing.JFrame {
     String nol_jam, nol_menit, nol_detik;
    
    

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        setTanggal();
        setJam();
        
        
    }
    
    
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        taa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tjumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kasir = new javax.swing.JTextField();
        b8 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        tharga = new javax.swing.JTextField();
        b9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Hasil1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdBarang", "Nama", "Jumlah", "Harga", "Tanggal", "NamaKasir", "Diskon", "Total"
            }
        ));
        jScrollPane2.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 790, 310);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(340, 260, 800, 330);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setLayout(null);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(90, 10, 110, 30);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(210, 10, 110, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(340, 10, 110, 30);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh);
        refresh.setBounds(460, 10, 110, 30);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(580, 10, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(340, 200, 800, 50);

        taa.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(taa);
        taa.setBounds(880, 0, 220, 40);

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setText("TOKO SAYA BAGUS");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(450, 110, 200, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Telp. 031-588-3242 Fax. 031-588-3212 ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(390, 160, 300, 20);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel8.setText("Jln. Soekarno Hatta Barat Blok D, Surabaya 60118, Jawa Timur, Indonesia");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(250, 140, 610, 20);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);
        jPanel1.add(id);
        id.setBounds(120, 70, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel1.setText("ID Barang");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel2.setText("Nama  Barang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 120, 130, 30);
        jPanel1.add(nama);
        nama.setBounds(120, 120, 190, 30);
        jPanel1.add(tjumlah);
        tjumlah.setBounds(120, 170, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel3.setText("Jumlah  Barang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 170, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel4.setText("Harga Barang");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 230, 130, 30);
        jPanel1.add(kasir);
        kasir.setBounds(120, 330, 190, 30);

        b8.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        b8.setText("Tanggal ");
        jPanel1.add(b8);
        b8.setBounds(10, 280, 90, 30);
        jPanel1.add(Tanggal);
        Tanggal.setBounds(120, 280, 190, 30);
        jPanel1.add(tharga);
        tharga.setBounds(120, 230, 190, 30);

        b9.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        b9.setText("Nama Kasir");
        jPanel1.add(b9);
        b9.setBounds(10, 330, 90, 30);

        jLabel6.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 18)); // NOI18N
        jLabel6.setText("INPUTKAN BARANG");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 20, 200, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 200, 320, 390);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icone-boutique-01.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(480, 20, 110, 100);

        Hasil1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jPanel4.add(Hasil1);
        Hasil1.setBounds(890, 30, 220, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1150, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String tanggal = dateFormat.format(Tanggal.getDate());
       
//       tanggal.setText(kal.format(skrg));
        
        if("".equals(kasir.getText())|| 
               "".equals(tharga.getText()) || 
                tanggal.equals("") || 
                nama.getText().equals("") ||  
                "".equals(id.getText()) || 
                "".equals(tjumlah.getText()))
        {
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }else{
                             
        int Total;
        int sub_total;
        int diskon = 10;
        int jumlah;
        int harga;
        int batas = 100000;
        
        String jumlahkotor = tjumlah.getText();
        jumlah = Integer.parseInt(jumlahkotor);
    
        String hargakotor = tharga.getText();
        harga = Integer.parseInt(hargakotor);
        
        sub_total = jumlah * harga;
        if(sub_total > batas){
            int hasil = (sub_total * diskon/100);
            Total = sub_total - hasil;
        }else{
            Total = sub_total;
            diskon = 0;
        }
               
           String SQL = "INSERT INTO tb_beli(IdBarang,Nama,Jumlah,Harga,Tanggal,NamaKasir,Diskon,Total)"
                   +"VALUES("+id.getText()
                   +",'"+nama.getText()
                   +"','"+tjumlah.getText()
                   +"','"+tharga.getText()
                   +"','"+tanggal
                   +"','"+kasir.getText()
                   +"','"+diskon
                   +"','"+Total+"')";
                   
           int status = KoneksiDB.execute(SQL);
           
           if(status == 1){
               JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
               selectData();
           }else{
               JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
           }
                   
    }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data!","",JOptionPane.YES_NO_OPTION);
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            String IdBarang = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_beli WHERE IdBarang='"+IdBarang+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Barisnya Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        id.setText("");
        nama.setText("");
        tjumlah.setText("");
        tharga.setText("");
        Tanggal.setDate(null);
        kasir.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat ("Biodata bla");
        MessageFormat footer = new MessageFormat ("bla");

        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch(java.awt.print.PrinterException e) {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil1;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kasir;
    private javax.swing.JTextField nama;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JLabel taa;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tjumlah;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"IdBarang","Nama","Jumlah","Harga","Tanggal","NamaKasir","Diskon","Total"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM tb_beli";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String IdBarang = rs.getString(1);
                String Nama = rs.getString(2);
                String Jumlah = rs.getString(3);
                String Harga = rs.getString(4);
                String Tanggal = rs.getString(5);
                String NamaKasir = rs.getString(6);
                String Diskon = rs.getString(7);
                String Total = rs.getString(8);
                String data[] = {IdBarang,Nama,Jumlah,Harga,Tanggal,NamaKasir,Diskon,Total};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE,null,ex);
        }
        
          tabel.setModel(dtm);   
    }
    
    public void setTanggal() {
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new
       java.text.SimpleDateFormat("dd/MM/yyyy");
       taa.setText(kal.format(skrg));
    }
    
    
    
    public void setJam() {
       ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
                
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if (nilai_jam<=9){
                    nol_jam = "0";
                } if (nilai_menit <= 9) {
                    nol_menit = "0";
                } if (nilai_detik <= 9){
                    nol_detik = "0";
                }
               
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Hasil1.setText(jam+":"+menit+":"+detik);
            }
        };
    new Timer(100, taskPerformer).start();
}
}
